builds/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

app_name = 'builds'

urlpatterns = [
    
    path('select_hero/', views.select_hero, name='select_hero'),
    path('create_build/<str:hero_name>', views.create_build, name='create_build'),
    path('view_build/<int:build_id>', views.view_build, name='view_build'),
    path('edit_build/<int:build_id>', views.edit_build, name='edit_build'),
    path('delete_build/<int:build_id>', views.delete_build, name='delete_build'),
    path('upvote/<int:build_id>', views.upvote, name='upvote'),
    path('downvote/<int:build_id>', views.downvote, name='downvote'),
    # path('<int:build_id>/exists', views.exists, name='exists'),
    
    
    

]
    

filtering/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

app_name = 'filtering'

urlpatterns = [
    path('select_content', views.select_content, name='select_content'),
    path('select_class', views.select_class, name='select_class'),
    path('select_hero', views.select_hero, name='select_hero'),
    path('custom_filter', views.custom_filter, name='custom_filter'),
    path('content/<str:content_value>', views.content, name='content'),
    path('hero_class/<str:hero_class>', views.hero_class, name='hero_class'),
    path('atk_type/<str:atk_type>', views.filter_atk_type, name='filter_atk_type'),
    path('hero_name/<str:hero_name>', views.hero_name, name='hero_name'),
    path('multi_filter', views.filter_custom_search, name='filter_custom_search'),
    
]
    

krbuilds/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import RedirectView
from django.contrib.staticfiles.storage import staticfiles_storage

from builds import views
# from filtering import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('builds/', include('builds.urls')),
    path('filtering/', include('filtering.urls')),
    path('top_teams/', include('top_teams.urls')),
    path('skills/', include('skills.urls')),
    path('accounts/dashboard', views.dashboard, name='dashboard'),
    # path('accounts/', include('accounts.urls', namespace='accounts')),
    path('', views.home, name='home'),
    path('new/', views.home_sort_by_new, name='home_sort_by_new'),
    path('terms_of_service', views.terms_of_service, name='terms_of_service'),
    path('privacy_policy', views.privacy_policy, name='privacy_policy'),
    path('about', views.about, name='about'),
    path('faqs', views.faqs, name='faqs'),
    # url(r'^accounts/', include('registration.backends.default.urls')),
    url(r'^accounts/', include('allauth.urls')),

    path('ads.txt', RedirectView.as_view(url=staticfiles_storage.url("ads.txt"))),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

filtering/models.py
from django.db import models

# Create your models here.

filtering/views.py
from django.shortcuts import render
from django.core.paginator import Paginator
from builds.models import Build, Hero, Content_Tag, HERO_CLASS_CHOICES
from .choices import hero_choices


def select_content(request):
    main_content = Content_Tag.objects.distinct('main_content')
    sub_content = Content_Tag.objects.all().order_by('sub_content')
    
    context = {
        'main_content': main_content,
        'sub_content': sub_content,

    }

    return render(request, 'select_content.html', context)

def select_class(request):
    # builds = Build.objects.filter(content_tags__icontains="")
    
    context = {
        'HERO_CLASS_CHOICES': HERO_CLASS_CHOICES,

    }

    return render(request, 'select_class.html', context)

def filter_atk_type(request, atk_type):
    builds = Build.objects.filter(hero__atk_type=atk_type).order_by('-vote_score')
    context = {
        'builds': builds,

    }
    return render(request, 'filter_content.html', context)

def custom_filter(request):
    # builds = Build.objects.order_by().distinct('hero')
    heroes = Hero.objects.order_by('hero_name')
    main_content = Content_Tag.objects.order_by('main_content').distinct('main_content')
    sub_content = Content_Tag.objects.all()

    context = {
        'heroes': heroes,
        'main_content': main_content,
        'sub_content': sub_content,
        'HERO_CLASS_CHOICES': HERO_CLASS_CHOICES,
    }
    return render(request, 'custom_filter.html', context)

def select_hero(request):
    # builds = Build.objects.filter(content_tags__icontains="")
    
    # heroes = Hero.objects.order_by('hero_name').values_list('hero_name', flat=True).distinct('hero_name')
    builds = Build.objects.order_by('hero').distinct('hero')

    context = {
        'builds': builds,
        # 'class_choices': class_choices,
        'hero_choices': hero_choices,

    }

    return render(request, 'select_hero.html', context)

def filter_custom_search(request):
    queryset_list = Build.objects.order_by('-vote_score')
    if request.method == 'GET':
        keywords = []

        # Hero Class
        if 'multi_filter_class' in request.GET:
            hero_class = request.GET['multi_filter_class']
            if hero_class:
                queryset_list = queryset_list.filter(hero__hero_class__iexact=hero_class)
                keywords.append(hero_class)

        # hero_class = request.GET.get('multi_filter_class') 

        # ATK Type
        if 'multi_filter_atk_type' in request.GET:
            atk_type = request.GET['multi_filter_atk_type']
            if atk_type:
                queryset_list = queryset_list.filter(hero__atk_type__iexact=atk_type)
                keywords.append(atk_type)

        # atk_type = request.GET.get('multi_filter_atk_type') 

        # Heroes
        if 'hero_name' in request.GET:
            hero_name = request.GET['hero_name']
            if hero_name:
                queryset_list = queryset_list.filter(hero__hero_name__iexact=hero_name)
                keywords.append(hero_name)
        
        # if 'hero_name' in request.GET:

        # Content Type - Main Content      

        # Content Type - Sub Content
        if 'sub_content' in request.GET:
            sub_content = request.GET['sub_content']
            if sub_content:
                # m_content = Content_Tag.objects.filter(main_content=main_content).first()
                queryset_list = queryset_list.filter(content_tags__icontains=sub_content)
                keywords.append(sub_content)

        # builds = Build.objects.filter(hero__hero_class=hero_class).filter(hero__atk_type=atk_type).order_by('-vote_score')
        # multi_header = hero_class + " + " + atk_type

        
        paginator = Paginator(queryset_list, 20)
        page = request.GET.get('page')
        builds_page = paginator.get_page(page)

        multi_header = ', '.join(keywords)
        
        context = {
            'builds': builds_page,            
            'multi_header': multi_header,
        }
        return render(request, 'filter_content.html', context)

def content(request, content_value):
    builds = Build.objects.filter(content_tags__icontains=content_value).order_by('-vote_score')
    
    context = {
        'builds': builds,
        'content_type': content_value,
    }
    return render(request, 'filter_content.html', context)

def hero_class(request, hero_class):
    builds = Build.objects.filter(hero__hero_class=hero_class).order_by('-vote_score')
    context = {
        'builds': builds,
        'hero_class': hero_class,
        
    }
    return render(request, 'filter_content.html', context)

def hero_name(request, hero_name):
    builds = Build.objects.filter(hero__hero_name=hero_name).order_by('-vote_score')
    context = {
        'builds': builds,
        'hero_name': hero_name,
        
    }
    return render(request, 'filter_content.html', context)

filtering/templates/custom_filter.html
{% extends 'base.html' %} 

{% block content %}

<!-- <h1>{{content_type}}</h1> -->
<h1>
    Custom Filtering
</h1>

<div class="container pt-3 mb-5">
    
  <p>You can combine filters to narrow down your search results.</p>

    <form action="{%url 'filtering:filter_custom_search' %}" method="GET" >
      {% csrf_token %}

      <div class="row">
          <div class="col">
              <p>Class</p>
              <select class="selectpicker" name="multi_filter_class">
                  <option selected></option>
                  {% for key,value in HERO_CLASS_CHOICES %}
                      <option value="{{key}}">{{ value }}</option> 
                  {% endfor %}
              </select>
          </div>

          <div class="col">
            <p>ATK Type</p>

            <select class="selectpicker" name="multi_filter_atk_type">
              <option selected></option>
              <option>Physical</option>
              <option>Magic</option>
            </select>
          </div>

          <div class="col">
            <p>Hero</p>

            <select name="hero_name" class="selectpicker" data-live-search="true" >
              <option value="" selected></option>
              {% for hero in heroes %}
                <option value="{{hero}}">{{ hero }}</option>
              {% endfor %}
            </select>
            
          </div>

         

         

      </div>

      <div class="row mt-3">

        <div class="col">
          <p>Content Type</p>

          <select name="sub_content" class="selectpicker" data-live-search="true">
            <option value="" selected></option>
            {% for tag in sub_content %}
              <option value="{{ tag.sub_content }}">{{ tag.main_content }}: {{ tag.sub_content }}</option>
            {% endfor %}
          </select>
        </div>

      </div>

      <div class="row">

        <div class="col">
          <p>&nbsp;</p>
          <button type="submit" class="btn btn-dark mb-2" >
              Go
          </button>
        </div>

        <div class="col text-right">
          <p>&nbsp;</p>
          <button type="button" class="btn btn-secondary" id="custom_search_clear">Clear</button>
        </div>

      </div>

  </form>

   
 

    



</div>



{% endblock %}

filtering/templates/filter_content.html
{% extends 'base.html' %} 

{% block content %}

<!-- <h1>{{content_type}}</h1> -->
<h1>
    {% firstof content_type hero_class hero_name multi_header %}
</h1>

<div class="container pt-3">
    {% if builds %}

        {% include 'builds/builds.html' %}
        
        {% include '_pagination.html' %}

    {% else %}

        <p>There are no submitted builds that meet your criteria.</p>

    {% endif %}
</div>



{% endblock %}

filtering/templates/select_class.html
{% extends 'base.html' %} 

{% block content %}

<h1 class="font-weight-light pb-3">Filter by Class</h1>

{% if HERO_CLASS_CHOICES %}
    
    
    
    {% for key,value in HERO_CLASS_CHOICES %}
        <div class="btn-group-toggle m-2 d-inline">
                
                <a class="btn btn-dark" href="{% url 'filtering:hero_class' key %}">{{ value }}</a>  
        </div>
    {% endfor %}

   
    
    


{% endif %}
        

{% endblock %}

filtering/templates/select_content.html
{% extends 'base.html' %} 

{% block content %}


{% if main_content %}

<h1 class="font-weight-light">Filter by Content</h1>

<p>Please select a category to view more options.</p>

<div class="accordion" id="accordionContentTags">
    <div class="card">
              
        {% for main_tag in main_content %}
            
            <div class="card" id="headingOne">
                
                <button class="btn btn-lg btn-light btn-block" type="button" data-toggle="collapse" data-target="#collapse{{forloop.counter}}" aria-expanded="true" aria-controls="collapseOne">
                    
                        {{ main_tag.main_content }}
                    
                </button>
                
            </div>  
            
            <div id="collapse{{forloop.counter}}" class="collapse" aria-labelledby="headingOne" data-parent="#accordionContentTags">
                <div class="card-body">
                    <div class="btn-group-toggle m-2">
                        
                        {% for sub_tag in sub_content  %}
                            {% if sub_tag.main_content == main_tag.main_content  %}
                                <a class="btn btn-dark m-1" href="{% url 'filtering:content' content_value=sub_tag.sub_content %}">{{ sub_tag.sub_content }}</a>
                        
                            {% endif %}
                        {% endfor %}
                    </div>
                </div>
            </div>

        {% endfor %}
               
    </div>
</div>

{% endif %}

        

{% endblock %}

filtering/templates/select_hero.html
{% extends 'base.html' %} 

{% block content %}

    <h1 class="font-weight-light ">Filter by Hero</h1>
    <h6 class="text-muted pb-3">Only heroes that have a submitted build will be shown.</h6>

    <!-- {% if heroes %}
        
        {% for hero in heroes %}

            
            {% if hero.hero_class == 'Knight' %}
                <label class="badge badge-light ">Knight: </label>   <br>
                <a class="btn btn-dark" href="{% url 'filtering:hero_name' hero %}">{{ hero }}</a> 
            {% endif %}
           
            {% if hero.hero_class == 'Warrior' %}
                <label class="badge badge-light ">Warrior: </label>   <br>
                <a class="btn btn-dark" href="{% url 'filtering:hero_name' hero %}">{{ hero }}</a> 
            {% endif %}
        {% endfor %}
        
    {% endif %} -->


    <!-- {% if heroes %}


        
        {% for hero in heroes %}
            <div class="btn-group-toggle m-2 d-inline">
                    <label class="badge badge-light ">{{ hero.hero_class }}: </label>   <br>
                    <a class="btn btn-dark" href="{% url 'filtering:hero_name' hero %}">{{ hero }}</a>  
            </div>
        {% endfor %}
    {% endif %} -->
    
   



    <!-- {% if hero_choices and heroes %}
            
        
        {% for class_name,hero_name in hero_choices.items %}
            
                
            <div class="btn-group-toggle m-2">
                <label class="badge badge-light ">{{ class_name }}: </label>   <br>
                {% for key,value in hero_name.items  %}
                   
                    {% if key in heroes %}
                        <a class="btn btn-dark" href="{% url 'filtering:hero_name' key %}">{{ value }}</a>
                    {% endif %}
                    
                {% endfor %}
            </div>
            
        {% endfor %}
        

    {% endif %} -->


    <div class="accordion" id="accordionContentTags">
        <div class="card">

            {% for class_name,hero_name in hero_choices.items %}

                <div class="card" id="headingOne">
                    <button class="btn btn-lg btn-light btn-block" type="button" data-toggle="collapse" data-target="#collapse{{forloop.counter}}" aria-expanded="true" aria-controls="collapseOne">
                    
                            {{ class_name }}
                        
                    </button>
                </div>

                <div id="collapse{{forloop.counter}}" class="collapse" aria-labelledby="headingOne" data-parent="#accordionContentTags">
                    <div class="card-body">
                        <div class="btn-group-toggle m-2">
                            <!-- <label class="badge badge-light ">{{ main_tags }}: </label>   <br> -->
                            {% for build in builds %}
            
                                {% for key,value in hero_name.items  %}
                                
                                    {% if key == build.hero.hero_name %}
                                        <a class="btn btn-dark" href="{% url 'filtering:hero_name' key %}">{{ value }}</a>
                                    {% endif %}
                                    
                                {% endfor %}
                            
                            {% endfor %}
                        </div>
                    </div>
                </div>

            {% endfor %}

        </div>
    </div>




<!-- 9/2/2019 -->
    <!-- {% for class_name,hero_name in hero_choices.items %}
        <div class="btn-group-toggle m-2">
            <label class="badge badge-light ">{{ class_name }}: </label>   <br>
            {% for build in builds %}
    
                    {% for key,value in hero_name.items  %}
                    
                        {% if key == build.hero.hero_name %}
                            <a class="btn btn-dark" href="{% url 'filtering:hero_name' key %}">{{ value }}</a>
                        {% endif %}
                        
                    {% endfor %}
                
            {% endfor %}
        </div>
    {% endfor %} -->

    <!-- Lists all the heroes names -->
    <!-- {% if hero_choices and heroes %}

        {% for class_name,hero_name in hero_choices.items %}
                
                    
            <div class="btn-group-toggle m-2">
                <label class="badge badge-light ">{{ class_name }}: </label>   <br>
                {% for key,value in hero_name.items  %}
                
                    {% if key in heroes %}
                        <a class="btn btn-dark" href="{% url 'filtering:hero_name' key %}">{{ value }}</a>
                    {% endif %}
                    
                {% endfor %}
            </div>
            
        {% endfor %}


    {% endif %} -->

{% endblock %}