accounts/urls.py
from django.urls import path
from . import views

# app_name = 'accounts'

urlpatterns = [
    path('user_login', views.user_login, name='user_login'),
    path('user_register', views.register, name='user_register'),
    path('user_logout', views.user_logout, name='user_logout'),
    path('dashboard', views.dashboard, name='dashboard'),

]

builds/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

app_name = 'builds'

urlpatterns = [
    
    path('select_hero/', views.select_hero, name='select_hero'),
    path('create_build/<str:hero_name>', views.create_build, name='create_build'),
    path('view_build/<int:build_id>', views.view_build, name='view_build'),
    path('edit_build/<int:build_id>', views.edit_build, name='edit_build'),
    path('delete_build/<int:build_id>', views.delete_build, name='delete_build'),
    path('upvote/<int:build_id>', views.upvote, name='upvote'),
    path('downvote/<int:build_id>', views.downvote, name='downvote'),
    # path('<int:build_id>/exists', views.exists, name='exists'),
    
    
    

]
    

krbuilds/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import RedirectView
from django.contrib.staticfiles.storage import staticfiles_storage

from builds import views
# from filtering import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('builds/', include('builds.urls')),
    path('filtering/', include('filtering.urls')),
    path('top_teams/', include('top_teams.urls')),
    path('skills/', include('skills.urls')),
    path('accounts/dashboard', views.dashboard, name='dashboard'),
    # path('accounts/', include('accounts.urls', namespace='accounts')),
    path('', views.home, name='home'),
    path('new/', views.home_sort_by_new, name='home_sort_by_new'),
    path('terms_of_service', views.terms_of_service, name='terms_of_service'),
    path('privacy_policy', views.privacy_policy, name='privacy_policy'),
    path('about', views.about, name='about'),
    path('faqs', views.faqs, name='faqs'),
    # url(r'^accounts/', include('registration.backends.default.urls')),
    url(r'^accounts/', include('allauth.urls')),

    path('ads.txt', RedirectView.as_view(url=staticfiles_storage.url("ads.txt"))),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models

# Create your models here.

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from builds.models import Build

def register(request):
    if request.method == 'POST':
        if request.POST['password1'] == request.POST['password2']:

            try:
                user = User.objects.get(username=request.POST['username'])
                return render(request, 'accounts/register.html', {'error':'Username has already been taken'}) 
            except User.DoesNotExist:
                user = User.objects.create_user(request.POST['username'], password=request.POST['password1'])
                login(request, user)
                return render(request, 'accounts/register.html') 
        else:
            return render(request, 'accounts/register.html', {'error':'Passwords didn\'t match'}) 
    else:
        return render(request, 'accounts/register.html')    

def user_login(request):
    if request.method == 'POST':
        user = authenticate(request, username=request.POST['username'], password=request.POST['password'])

        if user is not None:
            login(request, user)
            if 'next' in request.POST:
                return redirect(request.POST['next'])
            return redirect('home')
        else:
            return render(request, 'accounts/login.html', {'error':'The Username and Password didn\'t match'}) 
    else:
        return render(request, 'accounts/login.html')    

def user_logout(request):
    if request.method == 'POST':
        logout(request)
        return redirect('home')

def dashboard(request):
    user_builds = Build.objects.order_by('-created_at').filter(user_id=request.user.id)

    context = {
        'builds': user_builds
    }

    return render(request, 'accounts/dashboard.html', context)

accounts/templates/accounts/dashboard.html
{% extends 'base.html' %} 

{% block content %}


        

    
    <h1 class="font-weight-light text-center pb-3">My Builds</h1>
    
    

    
        {% if not builds %}

            <p>You have not posted any builds yet.</p>
            
        {% else %}
        <table class="table">
                <thead>
                    <tr class="text-center">
                        <th scope="col">Hero</th>
                        <th scope="col">Title</th>
                        <th scope="col">Date Created</th>
                        <th scope="col">Last Updated</th>
                        
                    </tr>
                </thead>

            {% for build in builds %}
            <tr class="text-center">
                
                <td>
                    {% with 'https://ik.imagekit.io/0h736tphh/krbuilds/hero/tr:n-55/'|add:build.hero.hero_name|add:'.png' as hero_img %}
                        <img class="rounded" src="{{ hero_img }}" alt=""> 
                    {% endwith %}      
                </td>
                <td>
                    <a href="{% url 'builds:view_build' build.id %}">{{ build.title }}</a>
                </td> 
                <td>
                    {{ build.created_at|date:"m/d/Y" }}
                </td>
                <td>
                    {{ build.updated_at|date:"m/d/Y" }}
                </td>
                <td>
                    <a class="btn btn-secondary" href="{% url 'builds:edit_build' build.id %}">Edit</a>
                </td>
                <td>
                    <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#deleteModal">
                        Delete
                    </button>
                </td>
    
    
                
            </tr>
    
            <!-- Modal -->

            <form action="{% url 'builds:delete_build' build.id %}" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModal" aria-hidden="true">
                    <div class="modal-dialog modal-dialog-centered" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                        
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                        </div>
                        <div class="modal-body">
                        Are you sure you want to delete this build?
                        </div>
                        <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                        <!-- <a class="btn btn-danger" href="{% url 'builds:delete_build' build.id %}">Delete</a> -->
                        <button class="btn btn-danger" type="submit">Delete</button>
                        </div>
                    </div>
                    </div>
                </div>
            </form>
                    
            {% endfor %}


        {% endif %}
    </table>
    

    <div style="height: 400px"></div>
            




{% endblock %}