builds/templates/builds/registration/backends/default/urls.py
"""
URLconf for registration and activation, using django-registration's
default backend.

If the default behavior of these views is acceptable to you, simply
use a line like this in your root URLconf to set up the default URLs
for registration::

    (r'^accounts/', include('registration.backends.default.urls')),

This will also automatically set up the views in
``django.contrib.auth`` at sensible default locations.

If you'd like to customize registration behavior, feel free to set up
your own URL patterns for these views instead.

"""


from django.conf import settings
from django.conf.urls import include
from django.conf.urls import url
from django.views.generic.base import TemplateView

from .views import ActivationView
from .views import RegistrationView
from .views import ResendActivationView

urlpatterns = [
    url(r'^activate/complete/$',
        TemplateView.as_view(template_name='registration/activation_complete.html'),
        name='registration_activation_complete'),
    url(r'^activate/resend/$',
        ResendActivationView.as_view(),
        name='registration_resend_activation'),
    # Activation keys get matched by \w+ instead of the more specific
    # [a-fA-F0-9]{40} because a bad activation key should still get to the view;
    # that way it can return a sensible "invalid key" message instead of a
    # confusing 404.
    url(r'^activate/(?P<activation_key>\w+)/$',
        ActivationView.as_view(),
        name='registration_activate'),
    url(r'^register/complete/$',
        TemplateView.as_view(template_name='registration/registration_complete.html'),
        name='registration_complete'),
    url(r'^register/closed/$',
        TemplateView.as_view(template_name='registration/registration_closed.html'),
        name='registration_disallowed'),
]

if getattr(settings, 'INCLUDE_REGISTER_URL', True):
    urlpatterns += [
        url(r'^register/$',
            RegistrationView.as_view(),
            name='registration_register'),
    ]

if getattr(settings, 'INCLUDE_AUTH_URLS', True):
    urlpatterns += [
        url(r'', include('registration.auth_urls')),
    ]

builds/templates/builds/registration/backends/simple/urls.py
"""
URLconf for registration and activation, using django-registration's
one-step backend.

If the default behavior of these views is acceptable to you, simply
use a line like this in your root URLconf to set up the default URLs
for registration::

    (r'^accounts/', include('registration.backends.simple.urls')),

This will also automatically set up the views in
``django.contrib.auth`` at sensible default locations.

If you'd like to customize registration behavior, feel free to set up
your own URL patterns for these views instead.

"""


from django.conf import settings
from django.conf.urls import include
from django.conf.urls import url
from django.views.generic.base import TemplateView

from .views import RegistrationView

urlpatterns = [
    url(r'^register/closed/$',
        TemplateView.as_view(template_name='registration/registration_closed.html'),
        name='registration_disallowed'),
]

if getattr(settings, 'INCLUDE_REGISTER_URL', True):
    urlpatterns += [
        url(r'^register/$',
            RegistrationView.as_view(
                success_url=getattr(settings, 'SIMPLE_BACKEND_REDIRECT_URL', '/'),
            ),
            name='registration_register'),
    ]

if getattr(settings, 'INCLUDE_AUTH_URLS', True):
    urlpatterns += [
        url(r'', include('registration.auth_urls')),
    ]

builds/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

app_name = 'builds'

urlpatterns = [
    
    path('select_hero/', views.select_hero, name='select_hero'),
    path('create_build/<str:hero_name>', views.create_build, name='create_build'),
    path('view_build/<int:build_id>', views.view_build, name='view_build'),
    path('edit_build/<int:build_id>', views.edit_build, name='edit_build'),
    path('delete_build/<int:build_id>', views.delete_build, name='delete_build'),
    path('upvote/<int:build_id>', views.upvote, name='upvote'),
    path('downvote/<int:build_id>', views.downvote, name='downvote'),
    # path('<int:build_id>/exists', views.exists, name='exists'),
    
    
    

]
    

filtering/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

app_name = 'filtering'

urlpatterns = [
    path('select_content', views.select_content, name='select_content'),
    path('select_class', views.select_class, name='select_class'),
    path('select_hero', views.select_hero, name='select_hero'),
    path('custom_filter', views.custom_filter, name='custom_filter'),
    path('content/<str:content_value>', views.content, name='content'),
    path('hero_class/<str:hero_class>', views.hero_class, name='hero_class'),
    path('atk_type/<str:atk_type>', views.filter_atk_type, name='filter_atk_type'),
    path('hero_name/<str:hero_name>', views.hero_name, name='hero_name'),
    path('multi_filter', views.filter_custom_search, name='filter_custom_search'),
    
]
    

krbuilds/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import RedirectView
from django.contrib.staticfiles.storage import staticfiles_storage

from builds import views
# from filtering import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('builds/', include('builds.urls')),
    path('filtering/', include('filtering.urls')),
    path('top_teams/', include('top_teams.urls')),
    path('skills/', include('skills.urls')),
    path('accounts/dashboard', views.dashboard, name='dashboard'),
    # path('accounts/', include('accounts.urls', namespace='accounts')),
    path('', views.home, name='home'),
    path('new/', views.home_sort_by_new, name='home_sort_by_new'),
    path('terms_of_service', views.terms_of_service, name='terms_of_service'),
    path('privacy_policy', views.privacy_policy, name='privacy_policy'),
    path('about', views.about, name='about'),
    path('faqs', views.faqs, name='faqs'),
    # url(r'^accounts/', include('registration.backends.default.urls')),
    url(r'^accounts/', include('allauth.urls')),

    path('ads.txt', RedirectView.as_view(url=staticfiles_storage.url("ads.txt"))),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

skills/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

app_name = 'skills'

urlpatterns = [
    path('', views.search_skills, name='search_skills'),

]
    

top_teams/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

app_name = 'top_teams'

urlpatterns = [
    
    path('', views.top_teams, name='top_teams'),
    path('view_teams/<str:content_type>', views.view_teams, name='view_teams'),
    path('create_team/<str:content_value>', views.create_team, name='create_team'),
    path('by_content/', views.by_content, name='by_content'),
    
    
    
    
    

]

builds/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.core.exceptions import ValidationError
from django.contrib import messages
from django.core.paginator import Paginator
from .models import Build, Hero, Content_Tag
from .choices import *
from .forms import BuildForm

from django import forms

def upvote(request, build_id):
    if request.method == 'POST':
        build = Build.objects.get(pk=build_id)
        # post.votes_total += 1
        if not build.votes.up(request.user.id):
            build.votes.delete(request.user.id)
        # post.save()
        # return redirect('home')
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

def downvote(request, build_id):
    if request.method == 'POST':
        build = Build.objects.get(pk=build_id)
        # post.votes_total -= 1
        if not build.votes.down(request.user.id):
            build.votes.delete(request.user.id)
        # post.save()
        # return redirect('home')
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

def home(request):
    # posts = Post.objects.order_by('-votes_total')
    # builds = Build.objects.all()
    builds = Build.objects.order_by('-vote_score')
    # for build in builds:
    #     build.content_tags = build.content_tags.split(' ')

    paginator = Paginator(builds, 20)
    page = request.GET.get('page')
    builds_page = paginator.get_page(page)

    context = {
        'builds': builds_page,
        
    }

    return render(request, 'home.html', context)

def home_sort_by_new(request):
    builds = Build.objects.order_by('-created_at')
    for build in builds:
        build.content_tags = build.content_tags.split(' ')

    paginator = Paginator(builds, 20)
    page = request.GET.get('page')
    builds_page = paginator.get_page(page)

    context = {
        'builds': builds_page,
        
    }

    return render(request, 'home.html', context)

def view_build(request, build_id):
    # build = Build.objects.filter(id__iexact=build_id)
    build = get_object_or_404(Build, pk=build_id)
    # tags = ''.join(build.content_tags).split('[]')
    tags = build.content_tags.strip('[]').replace("'", "").split(', ')
    
    context = {
        'build': build,
        'tags': tags,
        
    }

    return render(request, 'builds/view_build.html', context)

def dashboard(request):
    user_builds = Build.objects.order_by('-created_at').filter(user_id=request.user.id)

    context = {
        'builds': user_builds
    }

    return render(request, 'accounts/dashboard.html', context)

@login_required
def edit_build(request, build_id):
    build = Build.objects.get(pk=build_id)
    main_content = Content_Tag.objects.distinct('main_content')
    sub_content = Content_Tag.objects.all().order_by('sub_content')

    if '&' in build.runes_weapon1:
        runes_weapon1_velk = build.runes_weapon1.split(' & ')
    else:
        runes_weapon1_velk = ''

    if '&' in build.runes_weapon2:
        runes_weapon2_velk = build.runes_weapon2.split(' & ')
    else:
        runes_weapon2_velk = ''

    if '&' in build.runes_weapon3:
        runes_weapon3_velk = build.runes_weapon3.split(' & ')
    else:
        runes_weapon3_velk = ''

    if '&' in build.runes_armor:
        runes_armor_velk = build.runes_armor.split(' & ')
    else:
        runes_armor_velk = ''

    if '&' in build.runes_secondary:
        runes_secondary_velk = build.runes_secondary.split(' & ')
    else:
        runes_secondary_velk = ''
    

    if request.user == build.user:
         # instance = BuildForm.objects.get(pk=build_id)
        
        form = BuildForm(request.POST or None, instance=build)

        if request.method == "POST" and form.is_valid():
            # build = form.save(commit=False)
            # build.user = request.user
            # build.hero = build.hero

            form.save()

            messages.success(request, 'Build has been updated.')
            # return redirect(home)
            return redirect('builds:view_build', build_id=build_id)

        context = {
            'build': build,
            'gearset_quantity_choices': gearset_quantity_choices,
            'gearset_type_choices': gearset_type_choices,
            'unique_treasure_choices': unique_treasure_choices,
            'unique_treasure_options_choices': unique_treasure_options_choices,
            'gear_options_num_choices': gear_options_num_choices,
            'dropdown_stats_choices': dropdown_stats_choices,
            'enchants_choices': dropdown_stats_choices,
            'runes_weapons_choices': runes_weapons_choices,
            'runes_armor_choices': runes_armor_choices,
            'runes_secondary_choices': runes_secondary_choices,
            'accessory_type_choices': accessory_type_choices,
            # 'runes_velkazar_choices': runes_velkazar_choices,
            'runes_velkazar_95_choices': runes_velkazar_95_choices,
            'unique_treasure_num_choices': unique_treasure_num_choices,
            'runes_weapon1_velk': runes_weapon1_velk,
            'runes_weapon2_velk': runes_weapon2_velk,
            'runes_weapon3_velk': runes_weapon3_velk,
            'runes_armor_velk': runes_armor_velk,
            'runes_secondary_velk': runes_secondary_velk,
            'main_content': main_content,
            'sub_content': sub_content,
        }
        return render(request, 'builds/edit_build.html', context)

    else:
        return redirect(home)

@login_required
def delete_build(request, build_id):
    build = Build.objects.get(id=build_id)
    if request.user == build.user:
        if request.method == 'POST':
            # build = Build.objects.get(id=build_id)
            build.delete()
            return redirect('dashboard')
        else:
            return redirect('dashboard')
    else:
        return redirect('home')

@login_required(login_url='/accounts/login')
def select_hero(request):
    
    heroes = Hero.objects.all().order_by('hero_name')
    context = {
            'heroes': heroes,
            
        }
    return render(request, 'builds/create_build/select_hero.html', context)

@login_required(login_url='/accounts/login')
def create_build(request, hero_name):
    hero = Hero.objects.get(hero_name=hero_name)
    main_content = Content_Tag.objects.distinct('main_content')
    sub_content = Content_Tag.objects.all().order_by('sub_content')
    # artifacts = Artifact.objects.all()

    if request.method == 'POST': 
        form = BuildForm(request.POST or None)

        # check whether it's valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required
            build = form.save(commit=False)
            build.user = request.user
            build.hero = hero
            
            build.save()

            messages.success(request, 'Build created successfully.')

            # redirect to a new URL:
            return redirect('home')
        else:
            # form = BuildForm() 
            context = {
                'form': form,
                'hero': hero,
                'accessory_type_choices': accessory_type_choices,
                'dropdown_stats_choices': dropdown_stats_choices,
                'runes_velkazar_95_choices': runes_velkazar_95_choices,
                'unique_treasure_num_choices': unique_treasure_num_choices,
                'main_content': main_content,
                'sub_content': sub_content,
            }

            return render(request, 'builds/create_build.html', context)

    else: 
        form = BuildForm()

    context = {
        'form': form,
        'hero': hero,
        'accessory_type_choices': accessory_type_choices,
        'dropdown_stats_choices': dropdown_stats_choices,
        'runes_velkazar_95_choices': runes_velkazar_95_choices,
        'unique_treasure_num_choices': unique_treasure_num_choices,
        'main_content': main_content,
        'sub_content': sub_content,
    }
    return render(request, 'builds/create_build.html', context)
        
def privacy_policy(request):
    return render(request, 'footer/privacy_policy.html')

def terms_of_service(request):
    return render(request, 'footer/terms_of_service.html')

def about(request):
    return render(request, 'footer/about.html')

def faqs(request):
    return render(request, 'footer/faqs.html')

builds/templates/_pagination.html
{% if builds.has_other_pages %}
      
    <nav aria-label="Page navigation example">
        <ul class="pagination">
        {% if builds.has_previous %}
        <li class="page-item">
            <a href="?page={{builds.previous_page_number}}" class="page-link">&laquo;</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link">&laquo;</a>
        </li>
        {% endif %}
        {%  for i in builds.paginator.page_range %}
        {% if builds.number == i %}
            <li class="page-item active">
                <a class="page-link">{{i}}</a>
            </li>
        {% else %}
            <li class="page-item">
                <a href="?page={{i}}" class="page-link">{{i}}</a>
            </li>
        {% endif %}
        {% endfor %}
        {% if builds.has_next %}
        <li class="page-item">
            <a href="?page={{builds.next_page_number}}" class="page-link">&raquo;</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link">&raquo;</a>
        </li>
        {% endif %}
        </ul>
    </nav>

{% endif %}

builds/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="description" content="Build sharing platform for King's Raid. Come create, view, and share builds and guides with other players. ">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>KRBuilds</title>

    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <!-- Font Awesome -->
    
    <!-- Custom -->
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <link rel="stylesheet" href="{% static 'css/media_query.css' %}">

    <!-- Parsley CSS -->
    <link rel="stylesheet" href="https://parsleyjs.org/src/parsley.css">

    <!-- Bootstrap-Select CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.9/dist/css/bootstrap-select.min.css">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

    <script data-ad-client="ca-pub-4140495451115881" async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
    
  </head>
  <body class="bg_fill ">

    <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark static-top">
      <div class="container">
        <a class="navbar-brand" href="{% url 'home' %}">KR Builds</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav">
              <li class="nav-item ">
                <a class="nav-link" href="{% url 'top_teams:top_teams' %}">Top Teams</a>
              </li>
              <li class="nav-item ">
                <a class="nav-link" href="{% url 'skills:search_skills' %}">Skills</a>
              </li>
              <!--<li class="nav-item">
                <a class="nav-link" href="{% url 'filtering:select_content' %}">Filter by Content</a>
              </li> -->
              <li class="nav-item dropdown show">
                <a class="nav-link dropdown-toggle" href="#" role="button" id="navbarDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Filtering
                </a>
              
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <a class="dropdown-item" href="{% url 'filtering:select_content' %}">Filter by Content</a>
                  <a class="dropdown-item" href="{% url 'filtering:select_class' %}">Filter by Class</a>
                  <a class="dropdown-item" href="{% url 'filtering:select_hero' %}">Filter by Hero</a>
                  <div class="dropdown-divider"></div>
                  <a class="dropdown-item" href="{% url 'filtering:custom_filter' %}">Custom Filter</a>
                </div>
              </li>
              <li class="nav-item">
                
              </li>
              <li class="nav-item">
                
              </li>
              <li class="nav-item">
                
              </li>
          </ul>
          <ul class="navbar-nav ml-auto">
              
              <li class="nav-item"><a class="nav-link" href="{% url 'builds:select_hero' %}">New Build</a></li>
              <li class="nav-item"><a class="nav-link" href="{% url 'top_teams:by_content' %}">New Team</a></li>
              
              {% if user.is_authenticated %}
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">{{ user }}</a>
                <div class="dropdown-menu">
                  <a class="dropdown-item" href="{% url 'dashboard' %}">My Builds</a>
                  <div class="dropdown-divider"></div>
                  <!-- <a class="dropdown-item" href="#" onClick="document.getElementById('logout').submit()">Logout</a> -->
                  <a class="dropdown-item" href="{% url 'account_logout' %}" >Logout</a>
                </div>
              </li>

              <form id="logout" method="POST" action="">
                  {% csrf_token %}
                  <input type="hidden">
              </form>
              {% else %} 
              <li class="nav-item"><a class="nav-link" href="{% url 'account_signup' %}">Register</a></li>
              <li class="nav-item"><a class="nav-link" href="{% url 'account_login' %}">Login</a></li>
              {% endif %}

            
          </ul>
        </div>
      </div>
    </nav>

    <div class="row">
      <!-- Main: Left Vertical Ad -->
      <!-- <div class="col-xl-2 d-none d-xl-block">
           
        <div class="my-5 py-4">
            <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
             Left Vertical 300x600 
            <ins class="adsbygoogle"
                style="display:inline-block;width:300px;height:600px"
                data-ad-client="ca-pub-4140495451115881"
                data-ad-slot="3586784811"></ins>
            <script>
                (adsbygoogle = window.adsbygoogle || []).push({});
            </script>

        </div>      
        
      </div> -->
      
      

      <!-- <div class="col-xl-8"> -->
        <div class="container px-0">
                
          <ul class="nav navbar_sort nav-tabs mt-5">
              <li class="nav-item">
                  <a class="nav-link btn btn-sm btn-secondary nav_sort_btn py-0 {% if 'new' not in request.path %} active {% endif %}" href="{% url 'home' %}">Top</a>
              </li>
              <li class="nav-item">
                  <a class="nav-link btn btn-sm btn-secondary nav_sort_btn py-0 {% if 'new' in request.path %} active {% endif %}" href="{% url 'home_sort_by_new' %}">New</a>
              </li>
              
              
          </ul>

          <div class="card border-0 shadow mt-0 card_custom ">
              
              <div class="card-body ">
                  
                {% block content %} {% endblock %}
                {% include 'messages.html' %}
              </div>
          </div>
          
          
        </div>
      <!-- </div> -->


      <!-- Main: Right Vertical Ad Div -->
      <!-- <div class="col-xl-2 d-none d-xl-block">

        <div class="mt-5 py-4" >
          <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
           Right Vertical 300x600 
          <ins class="adsbygoogle"
              style="display:inline-block;width:300px;height:600px"
              data-ad-client="ca-pub-4140495451115881"
              data-ad-slot="1427525339"></ins>
          <script>
              (adsbygoogle = window.adsbygoogle || []).push({});
          </script>
          
        </div>        
        
      </div> -->

    </div>


    {% include 'footer/footer.html' %}
        

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    
    <!-- Bootstrap JS -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js" integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o" crossorigin="anonymous"></script>

    <!-- Font Awesome -->
    <script src="https://kit.fontawesome.com/00d370b5ca.js" crossorigin="anonymous"></script>
    <!-- Parsley JS -->
    <script src='{% static 'js/parsley.min.js' %}'></script>
    
    <!-- Bootstrap-Select -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.9/dist/js/bootstrap-select.min.js"></script>

    <!-- Custom JS -->
    <script src="{% static 'js/custom.js' %}"></script>
    <script src="{% static 'js/top_teams.js' %}"></script>

    <!-- Mark.js -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/mark.js/8.11.1/jquery.mark.min.js"></script>

    
  </body>
</html>

builds/templates/home.html
{% extends 'base.html' %} 

{% block content %}


<div class="container ">
      
   <div class="row">
         
   </div>

   {% include 'builds/builds.html' %}


   {% include '_pagination.html' %}


    
</div>




{% endblock %}

builds/templates/messages.html
<div class="messages_outer_div">
  {% for message in messages %}
  <div class="alert {{ message.tags }} alert-dismissible fade show" role="alert" id=message_alert>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    {{ message }}
  </div>
  {% endfor %}
</div>