builds/templates/builds/registration/backends/default/urls.py
"""
URLconf for registration and activation, using django-registration's
default backend.

If the default behavior of these views is acceptable to you, simply
use a line like this in your root URLconf to set up the default URLs
for registration::

    (r'^accounts/', include('registration.backends.default.urls')),

This will also automatically set up the views in
``django.contrib.auth`` at sensible default locations.

If you'd like to customize registration behavior, feel free to set up
your own URL patterns for these views instead.

"""


from django.conf import settings
from django.conf.urls import include
from django.conf.urls import url
from django.views.generic.base import TemplateView

from .views import ActivationView
from .views import RegistrationView
from .views import ResendActivationView

urlpatterns = [
    url(r'^activate/complete/$',
        TemplateView.as_view(template_name='registration/activation_complete.html'),
        name='registration_activation_complete'),
    url(r'^activate/resend/$',
        ResendActivationView.as_view(),
        name='registration_resend_activation'),
    # Activation keys get matched by \w+ instead of the more specific
    # [a-fA-F0-9]{40} because a bad activation key should still get to the view;
    # that way it can return a sensible "invalid key" message instead of a
    # confusing 404.
    url(r'^activate/(?P<activation_key>\w+)/$',
        ActivationView.as_view(),
        name='registration_activate'),
    url(r'^register/complete/$',
        TemplateView.as_view(template_name='registration/registration_complete.html'),
        name='registration_complete'),
    url(r'^register/closed/$',
        TemplateView.as_view(template_name='registration/registration_closed.html'),
        name='registration_disallowed'),
]

if getattr(settings, 'INCLUDE_REGISTER_URL', True):
    urlpatterns += [
        url(r'^register/$',
            RegistrationView.as_view(),
            name='registration_register'),
    ]

if getattr(settings, 'INCLUDE_AUTH_URLS', True):
    urlpatterns += [
        url(r'', include('registration.auth_urls')),
    ]

builds/templates/builds/registration/backends/simple/urls.py
"""
URLconf for registration and activation, using django-registration's
one-step backend.

If the default behavior of these views is acceptable to you, simply
use a line like this in your root URLconf to set up the default URLs
for registration::

    (r'^accounts/', include('registration.backends.simple.urls')),

This will also automatically set up the views in
``django.contrib.auth`` at sensible default locations.

If you'd like to customize registration behavior, feel free to set up
your own URL patterns for these views instead.

"""


from django.conf import settings
from django.conf.urls import include
from django.conf.urls import url
from django.views.generic.base import TemplateView

from .views import RegistrationView

urlpatterns = [
    url(r'^register/closed/$',
        TemplateView.as_view(template_name='registration/registration_closed.html'),
        name='registration_disallowed'),
]

if getattr(settings, 'INCLUDE_REGISTER_URL', True):
    urlpatterns += [
        url(r'^register/$',
            RegistrationView.as_view(
                success_url=getattr(settings, 'SIMPLE_BACKEND_REDIRECT_URL', '/'),
            ),
            name='registration_register'),
    ]

if getattr(settings, 'INCLUDE_AUTH_URLS', True):
    urlpatterns += [
        url(r'', include('registration.auth_urls')),
    ]

builds/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

app_name = 'builds'

urlpatterns = [
    
    path('select_hero/', views.select_hero, name='select_hero'),
    path('create_build/<str:hero_name>', views.create_build, name='create_build'),
    path('view_build/<int:build_id>', views.view_build, name='view_build'),
    path('edit_build/<int:build_id>', views.edit_build, name='edit_build'),
    path('delete_build/<int:build_id>', views.delete_build, name='delete_build'),
    path('upvote/<int:build_id>', views.upvote, name='upvote'),
    path('downvote/<int:build_id>', views.downvote, name='downvote'),
    # path('<int:build_id>/exists', views.exists, name='exists'),
    
    
    

]
    

krbuilds/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import RedirectView
from django.contrib.staticfiles.storage import staticfiles_storage

from builds import views
# from filtering import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('builds/', include('builds.urls')),
    path('filtering/', include('filtering.urls')),
    path('top_teams/', include('top_teams.urls')),
    path('skills/', include('skills.urls')),
    path('accounts/dashboard', views.dashboard, name='dashboard'),
    # path('accounts/', include('accounts.urls', namespace='accounts')),
    path('', views.home, name='home'),
    path('new/', views.home_sort_by_new, name='home_sort_by_new'),
    path('terms_of_service', views.terms_of_service, name='terms_of_service'),
    path('privacy_policy', views.privacy_policy, name='privacy_policy'),
    path('about', views.about, name='about'),
    path('faqs', views.faqs, name='faqs'),
    # url(r'^accounts/', include('registration.backends.default.urls')),
    url(r'^accounts/', include('allauth.urls')),

    path('ads.txt', RedirectView.as_view(url=staticfiles_storage.url("ads.txt"))),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

builds/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.core.exceptions import ValidationError
from django.contrib import messages
from django.core.paginator import Paginator
from .models import Build, Hero, Content_Tag
from .choices import *
from .forms import BuildForm

from django import forms

def upvote(request, build_id):
    if request.method == 'POST':
        build = Build.objects.get(pk=build_id)
        # post.votes_total += 1
        if not build.votes.up(request.user.id):
            build.votes.delete(request.user.id)
        # post.save()
        # return redirect('home')
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

def downvote(request, build_id):
    if request.method == 'POST':
        build = Build.objects.get(pk=build_id)
        # post.votes_total -= 1
        if not build.votes.down(request.user.id):
            build.votes.delete(request.user.id)
        # post.save()
        # return redirect('home')
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

def home(request):
    # posts = Post.objects.order_by('-votes_total')
    # builds = Build.objects.all()
    builds = Build.objects.order_by('-vote_score')
    # for build in builds:
    #     build.content_tags = build.content_tags.split(' ')

    paginator = Paginator(builds, 20)
    page = request.GET.get('page')
    builds_page = paginator.get_page(page)

    context = {
        'builds': builds_page,
        
    }

    return render(request, 'home.html', context)

def home_sort_by_new(request):
    builds = Build.objects.order_by('-created_at')
    for build in builds:
        build.content_tags = build.content_tags.split(' ')

    paginator = Paginator(builds, 20)
    page = request.GET.get('page')
    builds_page = paginator.get_page(page)

    context = {
        'builds': builds_page,
        
    }

    return render(request, 'home.html', context)

def view_build(request, build_id):
    # build = Build.objects.filter(id__iexact=build_id)
    build = get_object_or_404(Build, pk=build_id)
    # tags = ''.join(build.content_tags).split('[]')
    tags = build.content_tags.strip('[]').replace("'", "").split(', ')
    
    context = {
        'build': build,
        'tags': tags,
        
    }

    return render(request, 'builds/view_build.html', context)

def dashboard(request):
    user_builds = Build.objects.order_by('-created_at').filter(user_id=request.user.id)

    context = {
        'builds': user_builds
    }

    return render(request, 'accounts/dashboard.html', context)

@login_required
def edit_build(request, build_id):
    build = Build.objects.get(pk=build_id)
    main_content = Content_Tag.objects.distinct('main_content')
    sub_content = Content_Tag.objects.all().order_by('sub_content')

    if '&' in build.runes_weapon1:
        runes_weapon1_velk = build.runes_weapon1.split(' & ')
    else:
        runes_weapon1_velk = ''

    if '&' in build.runes_weapon2:
        runes_weapon2_velk = build.runes_weapon2.split(' & ')
    else:
        runes_weapon2_velk = ''

    if '&' in build.runes_weapon3:
        runes_weapon3_velk = build.runes_weapon3.split(' & ')
    else:
        runes_weapon3_velk = ''

    if '&' in build.runes_armor:
        runes_armor_velk = build.runes_armor.split(' & ')
    else:
        runes_armor_velk = ''

    if '&' in build.runes_secondary:
        runes_secondary_velk = build.runes_secondary.split(' & ')
    else:
        runes_secondary_velk = ''
    

    if request.user == build.user:
         # instance = BuildForm.objects.get(pk=build_id)
        
        form = BuildForm(request.POST or None, instance=build)

        if request.method == "POST" and form.is_valid():
            # build = form.save(commit=False)
            # build.user = request.user
            # build.hero = build.hero

            form.save()

            messages.success(request, 'Build has been updated.')
            # return redirect(home)
            return redirect('builds:view_build', build_id=build_id)

        context = {
            'build': build,
            'gearset_quantity_choices': gearset_quantity_choices,
            'gearset_type_choices': gearset_type_choices,
            'unique_treasure_choices': unique_treasure_choices,
            'unique_treasure_options_choices': unique_treasure_options_choices,
            'gear_options_num_choices': gear_options_num_choices,
            'dropdown_stats_choices': dropdown_stats_choices,
            'enchants_choices': dropdown_stats_choices,
            'runes_weapons_choices': runes_weapons_choices,
            'runes_armor_choices': runes_armor_choices,
            'runes_secondary_choices': runes_secondary_choices,
            'accessory_type_choices': accessory_type_choices,
            # 'runes_velkazar_choices': runes_velkazar_choices,
            'runes_velkazar_95_choices': runes_velkazar_95_choices,
            'unique_treasure_num_choices': unique_treasure_num_choices,
            'runes_weapon1_velk': runes_weapon1_velk,
            'runes_weapon2_velk': runes_weapon2_velk,
            'runes_weapon3_velk': runes_weapon3_velk,
            'runes_armor_velk': runes_armor_velk,
            'runes_secondary_velk': runes_secondary_velk,
            'main_content': main_content,
            'sub_content': sub_content,
        }
        return render(request, 'builds/edit_build.html', context)

    else:
        return redirect(home)

@login_required
def delete_build(request, build_id):
    build = Build.objects.get(id=build_id)
    if request.user == build.user:
        if request.method == 'POST':
            # build = Build.objects.get(id=build_id)
            build.delete()
            return redirect('dashboard')
        else:
            return redirect('dashboard')
    else:
        return redirect('home')

@login_required(login_url='/accounts/login')
def select_hero(request):
    
    heroes = Hero.objects.all().order_by('hero_name')
    context = {
            'heroes': heroes,
            
        }
    return render(request, 'builds/create_build/select_hero.html', context)

@login_required(login_url='/accounts/login')
def create_build(request, hero_name):
    hero = Hero.objects.get(hero_name=hero_name)
    main_content = Content_Tag.objects.distinct('main_content')
    sub_content = Content_Tag.objects.all().order_by('sub_content')
    # artifacts = Artifact.objects.all()

    if request.method == 'POST': 
        form = BuildForm(request.POST or None)

        # check whether it's valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required
            build = form.save(commit=False)
            build.user = request.user
            build.hero = hero
            
            build.save()

            messages.success(request, 'Build created successfully.')

            # redirect to a new URL:
            return redirect('home')
        else:
            # form = BuildForm() 
            context = {
                'form': form,
                'hero': hero,
                'accessory_type_choices': accessory_type_choices,
                'dropdown_stats_choices': dropdown_stats_choices,
                'runes_velkazar_95_choices': runes_velkazar_95_choices,
                'unique_treasure_num_choices': unique_treasure_num_choices,
                'main_content': main_content,
                'sub_content': sub_content,
            }

            return render(request, 'builds/create_build.html', context)

    else: 
        form = BuildForm()

    context = {
        'form': form,
        'hero': hero,
        'accessory_type_choices': accessory_type_choices,
        'dropdown_stats_choices': dropdown_stats_choices,
        'runes_velkazar_95_choices': runes_velkazar_95_choices,
        'unique_treasure_num_choices': unique_treasure_num_choices,
        'main_content': main_content,
        'sub_content': sub_content,
    }
    return render(request, 'builds/create_build.html', context)
        
def privacy_policy(request):
    return render(request, 'footer/privacy_policy.html')

def terms_of_service(request):
    return render(request, 'footer/terms_of_service.html')

def about(request):
    return render(request, 'footer/about.html')

def faqs(request):
    return render(request, 'footer/faqs.html')

builds/templates/builds/_sets.html
<option>Black Dragon (MP Recovery/Attack)</option>
<option>Frost Dragon (Max HP)</option>
<option>Fire Dragon (Crit)</option>
<option>Poison Dragon (Crit Resistance)</option>
<option>Lava (Crit Damage)</option>
<option>Legendary Eternal Flame (Debuff ACC)</option>
<option>Hero Suppression (Increases DMG to Heroes)</option>
<option>Hero Protection (Reduces DMG received from Heroes)</option>
<option>Dark Legion (Increases Crit DMG of all allies)</option>
<option>Beast of Chaos (Hero deals x% more DMG and takes x% less DMG from bosses)</option>

builds/templates/builds/_velkazar_runes.html
<option disabled>Velkazar Rune</option>
<option>ATK & Penetration</option>
<option>ATK & Crit</option>
<option>ATK & Crit DMG</option>
<option>ATK & ACC</option>
<option>ATK & Tough</option>
<option>ATK & DEF</option>
<option>ATK & Dodge</option>
<option>ATK & Block</option>
<option>ATK & MP Recovery/Attack</option>
<option>ATK & MAX HP</option>
<option>Crit & Penetration</option>
<option>Crit DMG & Penetration</option>
<option>Penetration & ACC</option>
<option>Penetration & Tough</option>
<option>DEF & Penetration</option>
<option>Penetration & Dodge</option>
<option>Penetration & Block</option>
<option>Penetration & MP Recovery/Attack</option>
<option>MAX HP & Penetration</option>
<option>Crit & Crit DMG</option>
<option>Crit & ACC</option>
<option>Crit & Tough</option>
<option>DEF & Crit</option>
<option>Crit & Dodge</option>
<option>Crit & Block</option>
<option>Crit & MP Recovery/Attack</option>
<option>MAX HP & Crit</option>
<option>Crit DMG & ACC</option>
<option>Crit DMG & Tough</option>
<option>DEF & Crit DMG</option>
<option>Crit DMG & Dodge</option>
<option>Crit DMG & Block</option>
<option>Crit DMG & MP Recovery/Attack</option>
<option>MAX HP & Crit DMG</option>
<option>ACC & Tough</option>
<option>DEF & ACC</option>
<option>ACC & Dodge</option>
<option>ACC & Block</option>
<option>ACC & MP Recovery/Attack</option>
<option>MAX HP & ACC</option>
<option>DEF & Tough</option>
<option>Dodge & Tough</option>
<option>Block & Tough</option>
<option>Tough & MP Recovery/Attack</option>
<option>MAX HP & Tough</option>
<option>DEF & Dodge</option>
<option>DEF & Block</option>
<option>DEF & MP Recovery/Attack</option>
<option>DEF & MAX HP</option>
<option>Dodge & Block</option>
<option>Dodge & MP Recovery/Attack</option>
<option>MAX HP & Dodge</option>
<option>Block & MP Recovery/Attack</option>
<option>MAX HP & Block</option>
<option>MAX HP & MP Recovery/Attack</option>

builds/templates/builds/builds.html
{% load static %}
{% load vote %}

{% for build in builds %}
<div class="row mb-2 ">
    <div class="col-md-7 col-sm-12 col-xl-7 col-lg-7 col-12 p-0">
        <div class="row mx-0">
            {% vote_exists build request.user 0 as vote_up %}
            {% vote_exists build request.user 1 as vote_down %}

            <!-- Vote Buttons & Karma Div -->
            <div class="parent-vote-div col-1 px-1">
                <div class="child-vote-div text-center">
                    <!-- <a href="#" onClick="document.getElementById('upvote{{ build.id }}').submit()"><span class="fas fa-chevron-up arrow_custom_color" aria-hidden="true"></span></a>   -->
                    <a href="#" onClick="document.getElementById('upvote{{ build.id }}').submit()"><span class="fas fa-chevron-up  {% if vote_up %} arrow_custom_color2 {% else %} arrow_custom_color {% endif %}" aria-hidden="true" ></span></a>  
                </div>
                <div class="child2-vote-div text-center text-dark">
                    
                    {{ build.vote_score }} 
                            
                </div>
                <div class="child3-vote-div text-center">
                    <a href="#" onClick="document.getElementById('downvote{{ build.id }}').submit()"><span class="fas fa-chevron-down {% if vote_down %} arrow_custom_color2 {% else %} arrow_custom_color {% endif %}" aria-hidden="true"></span></a>
                </div>
            </div>
            
            
            
            <form id="upvote{{ build.id }}" method="POST" action="{% url 'builds:upvote' build.id %}">
                {% csrf_token %}
                <input type="hidden" />
            </form>
            
            <form id="downvote{{ build.id }}" method="POST" action="{% url 'builds:downvote' build.id %}">
                {% csrf_token %}
                <input type="hidden" />
            </form>
            
            <!-- Hero Icon Div -->
            <div class="px-1 ">
                {% with 'https://ik.imagekit.io/0h736tphh/krbuilds/hero/tr:n-55/'|add:build.hero.hero_name|add:'.png' as hero_img %}
                    <img class="rounded" src="{{ hero_img }}" alt=""> 
                {% endwith %}                  
            </div>

            <!-- Title Author Date Div -->
            <div class="col-8 col-xl-9 col-lg-9 col-md-9 col-sm-9 ">
                <div class="title-author m-0">

                    <a class="home-title text-dark d-block text-truncate " href="{% url 'builds:view_build' build.id %}">{{ build.title }}</a>              

                    <h6 class="text-muted">submitted by: {{ build.user }}, last updated: {{ build.updated_at|date:"m-d-Y"  }}</h6> 
                        
                </div>
                
            </div>


        </div>
    </div>



    <div class="col-md-5 col-xl-5 col-lg-5">
        <div class="row">
            
            <!-- Position -->
            <div class="col p-1">
                <div class="position_icon bg-dark d-flex rounded">
                    {% if build.hero.position == 'Front' %}
                        <span class="border bg-light d-block text-center vertical-center  w-100 "><strong>Front</strong></span>
                    {% elif build.hero.position == 'Middle' %}
                        <span class="border bg-light d-block text-center vertical-center  w-100 "><strong>Mid</strong></span>
                    {% elif build.hero.position == 'Back' %}
                        <span class="border bg-light d-block text-center vertical-center  w-100 "><strong>Back</strong></span>
                    {% endif %}
                </div>
            </div>

            <div class="col p-1">
                
                <!-- Class Icon -->
                {% if build.hero.hero_class == 'Knight' %}
                    <img class="home-icon" src="{% static 'img/knight.png' %}" alt=""> 
                {% elif build.hero.hero_class == 'Wizard' %}
                    <img class="home-icon" src="{% static 'img/wizard.png' %}" alt=""> 
                {% elif build.hero.hero_class == 'Warrior' %}
                    <img class="home-icon" src="{% static 'img/warrior.png' %}" alt=""> 
                {% elif build.hero.hero_class == 'Assassin' %}
                    <img class="home-icon" src="{% static 'img/assassin.png' %}" alt=""> 
                {% elif build.hero.hero_class == 'Archer' %}
                    <img class="home-icon" src="{% static 'img/archer.png' %}" alt=""> 
                {% elif build.hero.hero_class == 'Mechanic' %}
                    <img class="home-icon" src="{% static 'img/mechanic.png' %}" alt=""> 
                {% elif build.hero.hero_class == 'Priest' %}
                    <img class="home-icon" src="{% static 'img/priest.png' %}" alt=""> 
                {% endif %}
                        
                    
                
            </div>

        
            <div class="col p-1">
                
                <!-- UT Icon -->
                {% with 'https://ik.imagekit.io/0h736tphh/krbuilds/tr:n-55/'|add:build.hero.hero_name|add:'_'|add:build.unique_treasure_skill_num|add:'.png' as hero_ut %}
                    <img class="home-icon rounded" src="{{ hero_ut }}" alt=""> 
                {% endwith %}
                
            </div>

            <!-- Accessory Type -->
            <div class="col p-1">
            {% if 'Ring' in build.accessory_type %}
                <img class="home-icon" src="{% static 'img/ring.jpg' %}" alt="">
            {% elif 'Earrings' in build.accessory_type %}
                <img class="home-icon" src="{% static 'img/earrings.jpg' %}" alt="">
            {% elif 'Bracelet' in build.accessory_type %}
                <img class="home-icon" src="{% static 'img/bracelet.jpg' %}" alt="">
            {% elif 'Necklace' in build.accessory_type %}
                <img class="home-icon" src="{% static 'img/necklace.jpg' %}" alt="">
            {% endif %}
                
            </div>

            <!-- ATK Type Icon -->
            <div class="col p-1">
                    
                {% if build.hero.atk_type == 'Physical' %}
                    <img class="home-icon" src="{% static 'img/physical.png' %}" alt=""> 
                {% elif build.hero.atk_type == 'Magic' %}
                    <img class="home-icon" src="{% static 'img/magic.png' %}" alt=""> 
                {% endif %}    
                
            </div>

        

        </div>
    </div>
    
   

    
</div>
{% endfor %}

builds/templates/builds/create_build.html
{% extends 'base.html' %} 
{% load static %}

{% block content %}

<div class="container show_velk">
  <form action="{%url 'builds:create_build' hero %}" method="POST" id="create_build_form" >
    {% csrf_token %}

    {% if form.errors %}
        {% for field in form %}
            {% for error in field.errors %}
                <div class="alert alert-danger">
                    <strong>{{ error|escape }}</strong>
                </div>
            {% endfor %}
        {% endfor %}
        {% for error in form.non_field_errors %}
            <div class="alert alert-danger">
                <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endif %}

    <div class="row">
        <div class="col">
            {% with 'https://ik.imagekit.io/0h736tphh/krbuilds/hero/tr:n-50/'|add:hero.hero_name|add:'.png' as hero_img %}
                <img class="rounded" src="{{ hero_img }}" alt=""> 
            {% endwith %}
            
        </div>
        <div class="col text-center">
            <h1 class="font-weight-light justify-content-center">Create Build</h1>
        </div>
        <div class="col text-right">
            <h4 class="text-muted">{{ hero.hero_name }}</h4>
        </div>
    </div>
    
    <div class="row">
        <div class="">
            
        </div>
        <div class="col">
            <div class="form-group">
                <input type="text" class="form-control" name="title" placeholder="Title" data-parsley-trigger="focusout" required data-parsley-maxlength="140" data-parsley-minlength="5">
            </div>
        </div>
        
    </div>
 
    
    <p></p>

    <!-- BEGIN -->

    <div class="row">
        <div class="col">
            <div class="d-flex"> <label class="badge badge-dark mr-3">Content Tags:* </label><div id="content-tag-errors"></div> </div>

            {% include './create_build/content_tags.html' %}
        </div>
    </div>
    
    <p></p>

    <div class="row">
        <div class="col">
            <label class="badge badge-dark ">Gear Set:* </label>
            <div class="row">
                <div class="col">
                    {% include './create_build/gearsets.html' %}
                </div>
                    
                
            </div>

            <div class="row">
                <div class="col">
                    <label class="badge badge-dark ">Gear Options:* </label>
                    {% include './create_build/gear_options.html' %}
                    
                </div>
                
            </div>


        </div>
        <div class="col">

            <div class="row">
                <div class="col">
                    {% include './create_build/runes.html' %}
                </div>
                
            </div>

            

            <div class="row mt-2">
                <div class="col">
                    <label class="badge badge-dark ">Enchants:* </label>
                    {% include './create_build/enchants.html' %}
                </div>
                   
                
            </div>

            <div class="row mt-1">
                <div class="col">
                    {% include './create_build/artifacts.html' %}
                </div>
                
            </div>

            

        </div>
        <div class="col">

            {% include './create_build/transcend_perks.html' %}
            
            <div class="row">  
                <div class="col">
                    <label class="badge badge-dark ">Unique Treasure:* </label>

                    {% include './create_build/unique_treasure.html' %}    
                </div>   
                <div class="col">
                    {% include './create_build/accessory_type.html' %}
                </div>
            </div>

            <div class="row mt-2">
                <div class="col">
                        <label class="badge badge-dark ">UT Options:* </label>
                        {% include './create_build/ut_options.html' %}
                    </div>
                </div>
        </div>
    </div>

    <div class="row p-3">
      <label class="badge badge-dark">Summary:</label>
      <textarea class="form-control" name="summary" rows="3" placeholder="Optional"></textarea>
    </div>

    <button type="submit" class="btn btn-dark mb-2" name="submit_build">
      Submit
    </button>
  </form>

</div>

{% endblock %}